### ISSUE TITLE
Automatically copy to clipboard after cleaning?

### ISSUE THREAD

**Issue by yymao** [yymao/html-cleaner#1]
I wonder if users would find the web app more friendly if it automatically copies the cleaned content to the clipboard after the user clicks the clean button?

The current behavior is that the user needs re-select and re-copy. 

I'm interested in hearing people's thought. Tagging some users who I know: @rmandelb @burchat @EiffL

**Comment by burchat** [comment]
I think that would be helpful -- if a message comes up explicitly saying it has been copied to the clipboard (after the border turns green).  BTW, I like the way the border turns green. :-)

**Comment by yymao** [comment]
Hi @rmandelb @burchat @EiffL: Thank you for your feedback. I wonder if you would be willing to test a beta version that includes automatically copying the cleaned text? 

You can access the beta version here: https://yymao.github.io/html-cleaner/beta

If you are willing to help, thank you, and feel free to send me test emails :slightly_smiling_face:. If you have multiple browsers installed on your computer and can test them all, that'd even better! No pressure of course. 

So far I've tested it on Chrome and Firefox on Linux.

**Comment by rmandelb** [comment]
I gave it a try on Chrome on my Mac and sent you a test email :)

This is nothing new, but I think it would be nice if the "Cleaned and copied!" notification stayed on the page a little longer.  Right now it fades rather quickly.

**Comment by yymao** [comment]
Thank you @rmandelb. I got your email; it works on Chrome on Mac :slightly_smiling_face: 

Double the time the notification stays on the beta version.

**Comment by yymao** [comment]
Thank you all. The beta version is now going online.
